apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: awst-io
  labels:
    region: ap-southeast-1
spec:
  forProvider:
    region: ap-southeast-1
    imageScanningConfiguration:
      scanOnPush: true
    imageTagMutability: IMMUTABLE
  publishConnectionDetailsTo: 
     name: awst-io-ecr-config
  providerConfigRef:
    name: aws-provider